### PR TITLE
Memory feature

### PR DESCRIPTION
**Pull request by VisusAdAstra**

### CODE REVIEW

**Comment by SwatiPareek** [comment]
Could you walk me through what these changes are supposed to do? 
I tried to test the AC function in your branch but the result does not really change. Should I see some sort of "browser list" like the code suggests?
image

**Comment by VisusAdAstra** [comment]
when you press cal it will add current equation to the datalist embedded in input text field

**Comment by SwatiPareek** [comment]
> 
> 
> when you press cal it will add current equation to the datalist embedded in input text field

Understood but this is happening at back-end only, right. How will users see the history and be able to access elements in this datalist (unless you plan on adding a separate PR for that).

**Comment by VisusAdAstra** [comment]
t

**Comment by SwatiPareek** [comment]
> 
> 
> t

This is 

> 
> 
> t

Oh okay I see it now. Nice!
One possible suggestion. 
 
We may either want to talk about this in the help menu and/or create a separate tiny button right next to the form entry called history because our users might be oblivious to it like I was. 

There doesn't seem to be a limit to the memory datalist. Do we want to create one? Or do we allow user to infinitely update calculator until they clear memory?

**Comment by SwatiPareek** [comment]
It looks pretty good, and I will approve this PR. 

One issue we must work on is adding memory feature to local version of app. 
This solution will not work for local app.

**Comment by VisusAdAstra** [comment]
for the button i don't think it difficult at least for the web version, also the necessity should be put into consideration, for ex people know to double click on the search bar to list previous entry or type the first character (google webpage). The local app i don't really understand the logic behind so maybe only Anik can integrate it.

**Comment by SwatiPareek** [comment]
I wouldn't assume people know to double click on the search bar but fair point about the button. Lets be sure to add it in our user guide/help. 

@neoJINXD  -- would you be able to work with Nguyen to help out for the local version memory feature?

**Pull request merged**
