### PR TITLE
Various changes to UI

### PR DESCRIPTION
**Pull request by EmanuelUnity3D**
Made a few last changes to the UI in terms of polish.

image

* Distinguished the calculator color from the background color.
* Made the help button more clear. It now looks more like the other buttons.
* Added a hover style to the buttons so that what is and is not a button is more clear. This also makes the buttons feel a little more responsive.
* Changed the style of the input and output fields so that they are a bit more obvious.
* Swapped the Rad with the Deg button so that the default is on the left.
* Added a separator between rad and deg to make the direction of the toggle a but more clear.
* Changed the font of the title so that we are no longer using the default font and the font of the input/output so that it is monospace.
* Centered calculator.

Nothing is final obviously. I'm personally not crazy about the colors that I put for the input and output fields but I didn't want to spend all weekend thinking about them. Let me know what you guys think. You'll have to run the changes to see what the hover and the mode buttons look like.

### CODE REVIEW

**Comment by VisusAdAstra** [comment]
I think Eternity should be in the middle?

**Comment by EmanuelUnity3D** [comment]
> I think Eternity should be in the middle?

It was originally, I moved it to the left cause I thought that it looked better since the help button is on the right. Maybe I'm alone in this though.

**Comment by EmanuelUnity3D** [comment]
Also, I made the input and output left aligned so that the > and = line up horizontally. Having the title on the left lines up with the input as well.

**Comment by EmanuelUnity3D** [comment]
We lost the hover effect on the help button. I think that it's because we changed the hover styles to use per-button class selectors. We should either assign the help button to one of those classes or create a new one for it.

**Comment by EmanuelUnity3D** [comment]
Also, should the dropdowns also have a hover effect?

**Comment by neoJINXD** [comment]
yeah got it, originally had both as operation so that they would have the hover darken, but now i put that on the button tag itself.
that added back a hover effect on help.
i dont think the dropdowns themselves should have a hover effect since they dont have anything happend when clicking them unlike the other buttons which we have.

**Comment by EmanuelUnity3D** [comment]
Is it intentional that the help button lightens up instead of darkening on hover? If so, everything seems good.

**Comment by EmanuelUnity3D** [comment]
Looks good to me. We just need approval from @cpotteck (my reviewer) and @VisusAdAstra (your reviewer).

**Comment by SwatiPareek** [comment]
> 
> 
> This color looks great.

Needs more purple imo

**Pull request merged**
