### PR TITLE
Made some style changes, removed some code that wasn't being used, fi…

### PR DESCRIPTION
**Pull request by EmanuelUnity3D**
Made some style changes, removed some code that wasn't being used, fixed bug with decimal to binary.

This isn't a huge PR. I'm just putting it here so that Tara can take a look at it in the spirit of our code review procedure,

### CODE REVIEW

**Comment by cpotteck** [comment]
I get an error when running tests that I don't get on Tara's branch (I think):

```
======================================================================
ERROR: test_binary (tests.test_output_display.TestOutputDisplayFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/I513207/school/comp-354/Eternity/tests/test_output_display.py", line 29, in test_binary
    self.assertEqual((display.convert_to_binary(6)), bin(6).replace("0b", ""))  # Test for positive integer
AttributeError: module 'functions.output_display' has no attribute 'convert_to_binary'
```

**Comment by cpotteck** [comment]
Other than that the refactoring looks ok and from my tests the binary-decimal features work well. If you can specify what bug this merge is supposed to fix I can test further.

**Comment by EmanuelUnity3D** [comment]
> I get an error when running tests that I don't get on Tara's branch (I think):
> 
> ```
> ======================================================================
> ERROR: test_binary (tests.test_output_display.TestOutputDisplayFunctions)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Users/I513207/school/comp-354/Eternity/tests/test_output_display.py", line 29, in test_binary
>     self.assertEqual((display.convert_to_binary(6)), bin(6).replace("0b", ""))  # Test for positive integer
> AttributeError: module 'functions.output_display' has no attribute 'convert_to_binary'
> ```

My bad. I forgot to refactor the test code with the new function names. Good catch.

**Comment by cpotteck** [comment]
So with the new commit that same test never completes (or takes very long to complete, I let it hang for 2min). Can you check if its successful for you?
Stack trace on keyboardInterrupt:
```
.......F..F......FF..^CTraceback (most recent call last):
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "/Users/cpotteck/opt/anaconda3/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Users/cpotteck/school/comp-354/Eternity/tests/test_output_display.py", line 30, in test_binary
    self.assertEqual((display.decimal_to_binary(-6)), bin(-6).replace("0b", ""))  # Test for negative integer
  File "/Users/cpotteck/school/comp-354/Eternity/functions/output_display.py", line 88, in decimal_to_binary
    binary_result = decimal_to_binary_integer(int(number))
  File "/Users/cpotteck/school/comp-354/Eternity/functions/output_display.py", line 44, in decimal_to_binary_integer
    number_to_store = value % 2
KeyboardInterrupt
```

**Comment by cpotteck** [comment]
Could be related to negative inputs to decimal to binary conversion. Just checked manually through the UI and it seems to hang too.

**Comment by EmanuelUnity3D** [comment]
> Could be related to negative inputs to decimal to binary conversion. Just checked manually through the UI and it seems to hang too. *edit: the same input seems to work fine in #48

Yeah I also realized this. I'm actually looking into it right now. It's really weird.

**Comment by EmanuelUnity3D** [comment]
I tried to change the integer casted float division used in the decimal to binary conversion for a floor division (since that's the pythonic way of doing it), but it seems to cause problems.

**Comment by EmanuelUnity3D** [comment]
I solved the bug but I actually discovered a couple of issues with the code as I was fixing it. I fixed what I saw but I think that we should have more robust testing for the base conversion code before we merge to staging. I will leave that to Tara once this branch is merged.

**Pull request merged**
